### PR TITLE
creates shared memory if it doesn't exist rather than depending on arcdps creating it

### PR DESCRIPTION
**Pull request by coderedart**
just copy pasted from taco's implementation.

### CODE REVIEW

**Comment by coderedart** [comment]
closes https://github.com/AsherGlick/Burrito/issues/20

**Comment by AsherGlick** [comment]
This is awkward and I apologize but I cannot review this PR. The taco dev has been very adamant about what their software license is, and it is incompatible with the GPL.

If this PR is just a couple lines that does something like
```
if (size of(memory file) == 0) {
    create_memory_file(MAX_MEMORY_FILE_SIZE)
}
```
then I can merge it if you can find the example to it in public documentation and use theirs instead. But I cannot pull code copied from taco without the original author's approval. (see taco issue number 2)

**Comment by coderedart** [comment]
It's just a syscall. Nothing about it is specific to taco.  just mentioned it as a futures reference to the related code from similar project. And this is c code which taco is CPP code, that's why we need to use sizeof (struct LinkedMem) compared to taco.
  More references
https://docs.microsoft.com/en-us/windows/win32/memory/creating-named-shared-memory

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createfilemappinga

**Comment by coderedart** [comment]
But if you insist I will make a different pr tomorrow 😜

**Comment by coderedart** [comment]
kinda my first PR. so i messed it up. help me Asher sempai :) i added 3 files instead of just the burrito_link file

**Comment by AsherGlick** [comment]
I recommend using [git restore](https://git-scm.com/docs/git-restore) to roll back the files you did not intend to submit and make a new commit that reverts them. After submitting you can use git restore again to roll back the roll back locally so you still have your changes on your machine.

**Comment by coderedart** [comment]
it feels big because of formatting changes, but i tried my best to stick to the reference docs of microsoft. checked that it works.

**Review by AsherGlick — APPROVED** [review]

**Pull request merged**
